#
dubbo:
  application:
    name: test-dubbo-brave-D
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]"
product: process